# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================
logging:
    level:
        ROOT: DEBUG
        al.ikubinfo.fjalorth: DEBUG

spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        platform: h2
        initialization-mode: always
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/fjalorth;DB_CLOSE_DELAY=-1
        username: fjalorth
        password:
        hikari:
            auto-commit: false
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: create

server:
    port: 8081




